on:
  schedule:
    - cron: '0 2 * * * '
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: revdeps-gdal

jobs:
  run-revdeps:
    runs-on: ${{ matrix.config.os }}
    container: ghcr.io/osgeo/gdal:ubuntu-full-latest
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          #- {os: macos-latest,   r: 'release'}
          #- {os: windows-latest, r: 'release'}
          #- {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          #- {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      #- uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      #- name: Desperate measures
      #  run: Rscript -e "install.packages('arrow', repos = c('https://apache.r-universe.dev', 'https://cloud.r-project.org'))"

      - name: Run revdeps
        run: Rscript -e 'source("R/revdep.R", echo = TRUE);revdep(); cleanup()'

      - name: Commit
        run: |
          git config --global user.name 'Michael Sumner'
          git config --global user.email 'mdsumner@gmail.com'
          git config --global --add safe.directory '*'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"
